# https://github.com/kdelfour/cloud9-docker
FROM kdelfour/cloud9-docker
MAINTAINER 3846masa <3846masahiro+git@gmail.com>

ENTRYPOINT ["node", "/cloud9/server.js", "--listen", "0.0.0.0", "-w", "/workspace"]
CMD ["-a", ":"]
